# Generated by Django 3.2.23 on 2024-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240317_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iamge',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
