# Generated by Django 3.2.23 on 2024-03-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iamge',
            new_name='image',
        ),
    ]
